/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-15-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class CRUDPermissionBeforSOQLDMLException extends Exception {
    //exception_createPermissionBeforeSQLDML(String typeOfSobject){
        //message of the exception 'You have no permission to insert an ' + typeOfSobject + ' reccord.'
    //}
}